# Generated by Django 4.2.2 on 2023-06-30 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("primary_email", models.EmailField(max_length=100)),
                ("secondary_email", models.EmailField(default="", max_length=100)),
                ("accounts_email", models.EmailField(default="", max_length=100)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be 12 digits with an optional "+" sign and without any spaces or special characters.',
                                regex="^\\+?\\d{12}$",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("postcode", models.CharField(blank=True, default="", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company_registration_nr",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("vat", models.CharField(blank=True, default="", max_length=15)),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sort_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "name_on_bank_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("date", models.DateField(blank=True, default=None, null=True)),
                ("start_time", models.TimeField(blank=True, default=None)),
                ("duration", models.IntegerField(default=2)),
                ("location", models.CharField(default="", max_length=120)),
                (
                    "cc_supplement",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, null=True
                    ),
                ),
                (
                    "travel_supplement",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, null=True
                    ),
                ),
                (
                    "extra_supplement",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=5, null=True
                    ),
                ),
                ("nr_of_crew", models.IntegerField(default=1)),
                (
                    "site_contact",
                    models.CharField(default="", max_length=120, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "categories_needed",
                    models.ManyToManyField(blank=True, to="core.category"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.client"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(
                        choices=[("Mr", "Mr."), ("Mrs", "Mrs."), ("Miss", "Miss.")],
                        max_length=5,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField(null=True)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be 12 digits with an optional "+" sign and without any spaces or special characters.',
                                regex="^\\+?\\d{12}$",
                            )
                        ],
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "next_of_kin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("nin", models.CharField(blank=True, max_length=20, null=True)),
                ("utr", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sort_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "name_on_bank_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "message_confirmation",
                    models.CharField(default="None", max_length=10),
                ),
                ("categories", models.ManyToManyField(blank=True, to="core.category")),
                ("documents", models.ManyToManyField(blank=True, to="core.document")),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="worker_events", to="core.event"
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="core.skill")),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="skills_needed",
            field=models.ManyToManyField(blank=True, to="core.skill"),
        ),
        migrations.AddField(
            model_name="event",
            name="workers",
            field=models.ManyToManyField(
                blank=True, related_name="events_workers", to="core.worker"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="documents",
            field=models.ManyToManyField(blank=True, to="core.document"),
        ),
    ]
