# Generated by Django 4.2.2 on 2023-07-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_category_client_document_event_skill_worker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
