# Generated by Django 4.2.2 on 2023-07-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_worker_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=20)),
                (
                    "msg_type",
                    models.CharField(
                        choices=[("sent", "Sent"), ("received", "Received")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.worker",
                    ),
                ),
            ],
        ),
    ]
