# Generated by Django 4.2.2 on 2023-07-11 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='accounts_email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 12 digits with an optional "+" sign and without any spaces or special characters.', regex='^\\+?\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='secondary_email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
    ]
