# Generated by Django 4.2.2 on 2023-07-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_client_accounts_email_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('po_number', models.CharField(default='', max_length=25)),
                ('crew_count', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('date_of_event', models.DateField(default=None)),
                ('total_for_single_event', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(default='', max_length=255, null=True)),
                ('extra_supplement', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cc_supplement', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('travel_supplement', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('paid_invoice', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
        ),
    ]
