# Generated by Django 4.2.2 on 2023-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_invoice_grand_total_remove_invoice_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='job_number',
            field=models.CharField(default='', max_length=120),
        ),
    ]
