# Generated by Django 4.2.2 on 2023-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='job_title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
