# Generated by Django 4.2.2 on 2023-07-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_invoice_total_for_single_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_for_single_event',
        ),
    ]
