# Generated by Django 4.2.2 on 2023-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_invoice_grand_total_alter_invoice_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_for_single_event',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
