# Generated by Django 4.2.2 on 2023-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_date_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cc_required',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
