# Generated by Django 4.2.2 on 2023-07-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_invoice_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='event',
        ),
        migrations.AddField(
            model_name='invoice',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='core.event'),
        ),
    ]
