# Generated by Django 4.2.2 on 2023-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_invoice_event_invoice_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('primary_email', models.EmailField(blank=True, max_length=100)),
                ('secondary_email', models.EmailField(blank=True, max_length=100)),
                ('accounts_email', models.EmailField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_reg_number', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='event',
            field=models.ManyToManyField(blank=True, to='core.event'),
        ),
    ]
