# Generated by Django 4.2.2 on 2023-07-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_settings_alter_invoice_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
