# Generated by Django 4.2.2 on 2023-07-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cc_required',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('7 days', '7 days'), ('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='14 days', max_length=100),
        ),
    ]
