# Generated by Django 4.2.2 on 2023-07-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_eventstatus_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Miss', 'Miss.')], max_length=5, null=True),
        ),
    ]
