# Generated by Django 4.2.2 on 2023-08-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_event_site_contact_alter_worker_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='name_on_bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
