# Generated by Django 4.2.2 on 2023-08-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_settings_bank_account_settings_name_on_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
