# Generated by Django 4.2.2 on 2023-08-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_worker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
