# Generated by Django 4.2.2 on 2023-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_invoice_paid_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
