# Generated by Django 4.2.2 on 2023-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_invoice_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='postcode',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='town',
            field=models.CharField(default='', max_length=120),
        ),
    ]
