# Generated by Django 4.2.2 on 2023-08-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_event_address_event_postcode_event_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
